### ISSUE TITLE
Write a file reader for linearisation rules

### ISSUE THREAD

**Issue by ftyers** [matxin/matxin-lineariser#10]
The linearisation rules will be in XML and look like:

```
<lineariser>

  <rule>
    <NODE si="root" pos="VERB" ord="2">
        <NODE si="subj" pos="NOUN" ord="1"/>
        <NODE si="dobj" pos="NOUN" ord="3"/>
    </NODE>
  </rule>

</lineariser>
```

This would implement:

```
l = (w_0: VERB, {w_1: (subj, NOUN), w_2: (dobj, NOUN)}
L = l => w_1, w_0, w_2
```

**Comment by m5w** [comment]
I'll get started on this, but the linearizer is supposed to write its own rules. This probably would be useful for deserialization, though, as the grammars are supposed to be human-comprehensible, so a human-readable format such as XML would be appropriate.

**Comment by ftyers** [comment]
Yes, but we also want the users to be able to write their own rules too :)

**Comment by m5w** [comment]
Okay. Could you please link to the task once it's made?

**Comment by m5w** [comment]
See the PR.
